### ISSUE TITLE
tests failed because requests is missing (?)

### ISSUE THREAD

**Issue by epaulson** [BrickSchema/Brick#136]
So I had a weird failure today. Fresh checkout of Brick (though a few changes to the equipment defs), Anaconda python, venv instead of conda for the virtual env. 'make test' gave me the below. Happy to ignore it and see what happens when I check in and try my PR, but in case you have any ideas, thought I'd share.

```
========================================= 24 passed in 338.73s (0:05:38) ==========================================
cd tests/integration && bash run_integration_tests.sh
++ ls convert_test.sh
+ for i in '`ls *_test.sh`'
+ bash convert_test.sh
+ pushd ../../tools/convert
~/development/Brick/tools/convert ~/development/Brick/tests/integration
+ python3 -m venv venv
+ source venv/bin/activate
++ deactivate nondestructive
++ '[' -n '' ']'
++ '[' -n '' ']'
++ '[' -n /bin/bash -o -n '' ']'
++ hash -r
++ '[' -n '' ']'
++ unset VIRTUAL_ENV
++ '[' '!' nondestructive = nondestructive ']'
++ VIRTUAL_ENV=/Users/cpaulser/development/Brick/tools/convert/venv
++ export VIRTUAL_ENV
++ _OLD_VIRTUAL_PATH='/Users/cpaulser/development/Brick/venv/bin:/Users/cpaulser/anaconda3/bin:/Users/cpaulser/anaconda3/condabin:/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools'
++ PATH='/Users/cpaulser/development/Brick/tools/convert/venv/bin:/Users/cpaulser/development/Brick/venv/bin:/Users/cpaulser/anaconda3/bin:/Users/cpaulser/anaconda3/condabin:/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools'
++ export PATH
++ '[' -n '' ']'
++ '[' -z '' ']'
++ _OLD_VIRTUAL_PS1=
++ '[' 'x(venv) ' '!=' x ']'
++ PS1='(venv) '
++ export PS1
++ '[' -n /bin/bash -o -n '' ']'
++ hash -r
+ pip install -r requirements.txt
Collecting Dijkstar==2.4.0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/87/47/99c60dc0257c751ba59e31cc72f044d5f9d90c1f8960418723e2812d6bb0/Dijkstar-2.4.0.tar.gz
Collecting isodate==0.6.0 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/9b/9f/b36f7774ff5ea8e428fdcfc4bb332c39ee5b9362ddd3d40d9516a55221b2/isodate-0.6.0-py2.py3-none-any.whl
Collecting pyparsing==2.4.2 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/11/fa/0160cd525c62d7abd076a070ff02b2b94de589f1a9789774f17d7c54058e/pyparsing-2.4.2-py2.py3-none-any.whl (65kB)
    100% |████████████████████████████████| 71kB 1.1MB/s 
Collecting rdflib>=5.0.0 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/d0/6b/6454aa1db753c0f8bc265a5bd5c10b5721a4bb24160fb4faf758cf6be8a1/rdflib-5.0.0-py3-none-any.whl
Collecting six==1.12.0 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting tqdm==4.36.1 (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/e1/c1/bc1dba38b48f4ae3c4428aea669c5e27bd5a7642a74c8348451e0bd8ff86/tqdm-4.36.1-py2.py3-none-any.whl (52kB)
    100% |████████████████████████████████| 61kB 4.6MB/s 
Installing collected packages: Dijkstar, six, isodate, pyparsing, rdflib, tqdm
  Running setup.py install for Dijkstar ... done
Successfully installed Dijkstar-2.4.0 isodate-0.6.0 pyparsing-2.4.2 rdflib-5.0.0 six-1.12.0 tqdm-4.36.1
You are using pip version 19.0.3, however version 20.2b1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
++ ls examples/ebu3b_brick.ttl examples/ghc_brick.ttl examples/gtc_brick.ttl examples/rice_brick.ttl examples/soda_brick.ttl
+ for i in '`ls examples/*.ttl`'
+ python convert.py --source 1.0.2 --target 1.1 examples/ebu3b_brick.ttl
Traceback (most recent call last):
  File "convert.py", line 82, in <module>
    convert(args.source, args.target, args.models)
  File "convert.py", line 53, in convert
    % (source, target)
  File "/Users/cpaulser/development/Brick/tools/convert/venv/lib/python3.7/site-packages/rdflib/graph.py", line 1127, in query
    result = plugin.get(result, query.Result)
  File "/Users/cpaulser/development/Brick/tools/convert/venv/lib/python3.7/site-packages/rdflib/plugin.py", line 107, in get
    return p.getClass()
  File "/Users/cpaulser/development/Brick/tools/convert/venv/lib/python3.7/site-packages/rdflib/plugin.py", line 69, in getClass
    module = __import__(self.module_path, globals(), locals(), [""])
  File "/Users/cpaulser/development/Brick/tools/convert/venv/lib/python3.7/site-packages/rdflib/plugins/sparql/__init__.py", line 37, in <module>
    from .processor import prepareQuery, processUpdate
  File "/Users/cpaulser/development/Brick/tools/convert/venv/lib/python3.7/site-packages/rdflib/plugins/sparql/processor.py", line 18, in <module>
    from rdflib.plugins.sparql.evaluate import evalQuery
  File "/Users/cpaulser/development/Brick/tools/convert/venv/lib/python3.7/site-packages/rdflib/plugins/sparql/evaluate.py", line 20, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
make: *** [test] Error 1
(venv) (base) jci-mbp18:Brick cpaulser$ pip install requests
Requirement already satisfied: requests in ./venv/lib/python3.7/site-packages (2.23.0)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.7/site-packages (from requests) (2020.4.5.1)
Requirement already satisfied: idna<3,>=2.5 in ./venv/lib/python3.7/site-packages (from requests) (2.9)
Requirement already satisfied: chardet<4,>=3.0.2 in ./venv/lib/python3.7/site-packages (from requests) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./venv/lib/python3.7/site-packages (from requests) (1.25.9)
You are using pip version 19.0.3, however version 20.2b1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(venv) (base) jci-mbp18:Brick cpaulser$

**Comment by gtfierro** [comment]
Thanks for the bug report!

Thought I had fixed this, but I guess I never got around to it. Should be a one-line fix. I'll submit a PR soon and then you can merge from master and this should work

**Comment by gtfierro** [comment]
Should be fixed as of https://github.com/BrickSchema/Brick/pull/138; can you try a fresh clone and try again?

**Comment by epaulson** [comment]
Seems to be successful:
```
tests/test_subclass_hierarchy.py::test_cycles PASSED

========================================= 24 passed in 346.65s (0:05:46) ==========================================
cd tests/integration && bash run_integration_tests.sh
++ ls convert_test.sh
+ for i in '`ls *_test.sh`'
+ bash convert_test.sh
+ pushd ../../tools/convert
~/development/temp-Brick/Brick/tools/convert ~/development/temp-Brick/Brick/tests/integration
+ python3 -m venv venv
+ source venv/bin/activate
++ deactivate nondestructive
++ '[' -n '' ']'
++ '[' -n '' ']'
++ '[' -n /bin/bash -o -n '' ']'
++ hash -r
++ '[' -n '' ']'
++ unset VIRTUAL_ENV
++ '[' '!' nondestructive = nondestructive ']'
++ VIRTUAL_ENV=/Users/cpaulser/development/temp-Brick/Brick/tools/convert/venv
++ export VIRTUAL_ENV
++ _OLD_VIRTUAL_PATH='/Users/cpaulser/development/temp-Brick/Brick/venv/bin:/Users/cpaulser/anaconda3/bin:/Users/cpaulser/anaconda3/condabin:/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools'
++ PATH='/Users/cpaulser/development/temp-Brick/Brick/tools/convert/venv/bin:/Users/cpaulser/development/temp-Brick/Brick/venv/bin:/Users/cpaulser/anaconda3/bin:/Users/cpaulser/anaconda3/condabin:/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools'
++ export PATH
++ '[' -n '' ']'
++ '[' -z '' ']'
++ _OLD_VIRTUAL_PS1=
++ '[' 'x(venv) ' '!=' x ']'
++ PS1='(venv) '
++ export PS1
++ '[' -n /bin/bash -o -n '' ']'
++ hash -r
+ pip install -r requirements.txt
Collecting Dijkstar==2.4.0 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/87/47/99c60dc0257c751ba59e31cc72f044d5f9d90c1f8960418723e2812d6bb0/Dijkstar-2.4.0.tar.gz
Collecting isodate==0.6.0 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/9b/9f/b36f7774ff5ea8e428fdcfc4bb332c39ee5b9362ddd3d40d9516a55221b2/isodate-0.6.0-py2.py3-none-any.whl
Collecting pyparsing==2.4.2 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/11/fa/0160cd525c62d7abd076a070ff02b2b94de589f1a9789774f17d7c54058e/pyparsing-2.4.2-py2.py3-none-any.whl
Collecting rdflib>=5.0.0 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/d0/6b/6454aa1db753c0f8bc265a5bd5c10b5721a4bb24160fb4faf758cf6be8a1/rdflib-5.0.0-py3-none-any.whl
Collecting six==1.12.0 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting tqdm==4.36.1 (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/e1/c1/bc1dba38b48f4ae3c4428aea669c5e27bd5a7642a74c8348451e0bd8ff86/tqdm-4.36.1-py2.py3-none-any.whl
Collecting requests (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl
Collecting chardet<4,>=3.0.2 (from requests->-r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->-r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/57/2b/26e37a4b034800c960a00c4e1b3d9ca5d7014e983e6e729e33ea2f36426c/certifi-2020.4.5.1-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->-r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/e1/e5/df302e8017440f111c11cc41a6b432838672f5a70aa29227bf58149dc72f/urllib3-1.25.9-py2.py3-none-any.whl
Collecting idna<3,>=2.5 (from requests->-r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/89/e3/afebe61c546d18fb1709a61bee788254b40e736cff7271c7de5de2dc4128/idna-2.9-py2.py3-none-any.whl
Installing collected packages: Dijkstar, six, isodate, pyparsing, rdflib, tqdm, chardet, certifi, urllib3, idna, requests
  Running setup.py install for Dijkstar ... done
Successfully installed Dijkstar-2.4.0 certifi-2020.4.5.1 chardet-3.0.4 idna-2.9 isodate-0.6.0 pyparsing-2.4.2 rdflib-5.0.0 requests-2.23.0 six-1.12.0 tqdm-4.36.1 urllib3-1.25.9
You are using pip version 19.0.3, however version 20.2b1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
++ ls examples/ebu3b_brick.ttl examples/ghc_brick.ttl examples/gtc_brick.ttl examples/rice_brick.ttl examples/soda_brick.ttl
+ for i in '`ls examples/*.ttl`'
+ python convert.py --source 1.0.2 --target 1.1 examples/ebu3b_brick.ttl
Conversion available!
=====================
1.0.2 -> 1.1


Updating examples/ebu3b_brick.ttl...
Converting to 1.1...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████
Output stored: examples/ebu3b_brick(v1.1).ttl
+ for i in '`ls examples/*.ttl`'
+ python convert.py --source 1.0.2 --target 1.1 examples/ghc_brick.ttl
Conversion available!
=====================
1.0.2 -> 1.1


Updating examples/ghc_brick.ttl...
Converting to 1.1...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████
Output stored: examples/ghc_brick(v1.1).ttl
+ for i in '`ls examples/*.ttl`'
+ python convert.py --source 1.0.2 --target 1.1 examples/gtc_brick.ttl
Conversion available!
=====================
1.0.2 -> 1.1


Updating examples/gtc_brick.ttl...
Converting to 1.1...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████
Output stored: examples/gtc_brick(v1.1).ttl
+ for i in '`ls examples/*.ttl`'
+ python convert.py --source 1.0.2 --target 1.1 examples/rice_brick.ttl
Conversion available!
=====================
1.0.2 -> 1.1


Updating examples/rice_brick.ttl...
Converting to 1.1...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████
Output stored: examples/rice_brick(v1.1).ttl
+ for i in '`ls examples/*.ttl`'
+ python convert.py --source 1.0.2 --target 1.1 examples/soda_brick.ttl
Conversion available!
=====================
1.0.2 -> 1.1


Updating examples/soda_brick.ttl...
Converting to 1.1...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████
Output stored: examples/soda_brick(v1.1).ttl
+ deactivate
+ '[' -n '/Users/cpaulser/development/temp-Brick/Brick/venv/bin:/Users/cpaulser/anaconda3/bin:/Users/cpaulser/anaconda3/condabin:/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools' ']'
+ PATH='/Users/cpaulser/development/temp-Brick/Brick/venv/bin:/Users/cpaulser/anaconda3/bin:/Users/cpaulser/anaconda3/condabin:/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools'
+ export PATH
+ unset _OLD_VIRTUAL_PATH
+ '[' -n '' ']'
+ '[' -n /bin/bash -o -n '' ']'
+ hash -r
+ '[' -n '' ']'
+ unset VIRTUAL_ENV
+ '[' '!' '' = nondestructive ']'
+ unset -f deactivate
+ rm -rf venv
+ rm -rf 'examples/ebu3b_brick(v1.1).ttl' examples/ebu3b_brick.ttl 'examples/ghc_brick(v1.1).ttl' examples/ghc_brick.ttl 'examples/gtc_brick(v1.1).ttl' examples/gtc_brick.ttl 'examples/rice_brick(v1.1).ttl' examples/rice_brick.ttl 'examples/soda_brick(v1.1).ttl' examples/soda_brick.ttl
+ git checkout 'examples/*.ttl'
Updated 5 paths from the index
+ popd
~/development/temp-Brick/Brick/tests/integration
(venv) (base) jci-mbp18:Brick cpaulser$
```

**Comment by gtfierro** [comment]
Thanks for verifying! Closing the issue
