### ISSUE TITLE
Unable to `make test`

### ISSUE THREAD

**Issue by corymosiman12** [BrickSchema/Brick#206]
Following the `CONTRIBUTING` guidelines, getting the following error:

```
cmosiman-34078s:Brick cmosiman$ make test
python generate_brick.py
2021-01-12:19:44:54,227 WARNING [inference.py:128] Reasonable not installed; trying Allegro
Checking 55 containers
Traceback (most recent call last):
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.40/containers/63ea6498fc3033af5156fc5e734d2970c9b1dc143bc5ff7caf1a3ea0a73b421b/exec

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate_brick.py", line 29, in <module>
    from bricksrc.quantities import quantity_definitions, get_units
  File "/Users/cmosiman/Github/Brick/bricksrc/quantities.py", line 13, in <module>
    g = sess.expand(g)
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/brickschema/inference.py", line 57, in expand
    self.g = self._owl_sess.expand(self.g)
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/brickschema/inference.py", line 146, in expand
    return self.sess.expand(graph)
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/brickschema/inference.py", line 334, in expand
    check_error(agraph.exec_run("chown -R agraph /tmp", user="root"))
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/docker/models/containers.py", line 196, in exec_run
    workdir=workdir,
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/docker/api/exec_api.py", line 80, in exec_create
    return self._result(res, True)
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.40/containers/63ea6498fc3033af5156fc5e734d2970c9b1dc143bc5ff7caf1a3ea0a73b421b/exec: Conflict ("Container 63ea6498fc3033af5156fc5e734d2970c9b1dc143bc5ff7caf1a3ea0a73b421b is not running")
make: *** [Brick.ttl] Error 1
```

I've tried removing the container with that image and doing again with the same results.  Am I missing something?

Python 3.7.4

**Comment by gtfierro** [comment]
Can you show me how you are removing the `allegro` container? When I hit this error, I can usually just re-run the test command and it fixes itself

**Comment by corymosiman12** [comment]
I just 'docker container rm <id>'

**Comment by gtfierro** [comment]
- Do you hit the same error when you re-run `make test`? (Make sure you are only running one of these at a time)
- Can you send me the logs for the `allegro` container? The error seems to be occurring because the container is stopped, but its not clear to me yet why it would stop

**Comment by corymosiman12** [comment]
```
cmosiman-34078s:Brick cmosiman$ docker ps -a | grep agra
63ea6498fc30        franzinc/agraph:v7.0.0                        "/entrypoint.sh"          17 hours ago        Exited (1) 17 hours ago                                                      agraph
cmosiman-34078s:Brick cmosiman$ docker container rm 63ea6498fc30
63ea6498fc30
cmosiman-34078s:Brick cmosiman$ docker ps -a | grep agra
cmosiman-34078s:Brick cmosiman$ make test
python generate_brick.py
2021-01-13:12:24:12,198 WARNING [inference.py:128] Reasonable not installed; trying Allegro
Checking 55 containers
Non-zero exit code 126 with message b'OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "process_linux.go:101: executing setns process caused \\"exit status 1\\"": unknown\r\n'
Non-zero exit code 126 with message b'cannot exec in a stopped state: unknown\r\n'
Non-zero exit code 126 with message b'cannot exec in a stopped state: unknown\r\n'
Non-zero exit code 126 with message b'cannot exec in a stopped state: unknown\r\n'
Non-zero exit code 126 with message b'cannot exec in a stopped state: unknown\r\n'
Traceback (most recent call last):
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.40/containers/92410ae601ccda880e6d78fb752af83f18a883eefa2d7b6eafce6d85b461c2f9/archive?path=%2Ftmp%2Foutput.ttl

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate_brick.py", line 29, in <module>
    from bricksrc.quantities import quantity_definitions, get_units
  File "/Users/cmosiman/Github/Brick/bricksrc/quantities.py", line 13, in <module>
    g = sess.expand(g)
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/brickschema/inference.py", line 57, in expand
    self.g = self._owl_sess.expand(self.g)
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/brickschema/inference.py", line 146, in expand
    return self.sess.expand(graph)
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/brickschema/inference.py", line 362, in expand
    bits, stat = agraph.get_archive("/tmp/output.ttl")
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/docker/models/containers.py", line 262, in get_archive
    chunk_size, encode_stream)
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/docker/api/container.py", line 750, in get_archive
    self._raise_for_status(res)
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.40/containers/92410ae601ccda880e6d78fb752af83f18a883eefa2d7b6eafce6d85b461c2f9/archive?path=%2Ftmp%2Foutput.ttl: Not Found ("Could not find the file /tmp/output.ttl in container 92410ae601ccda880e6d78fb752af83f18a883eefa2d7b6eafce6d85b461c2f9")
make: *** [Brick.ttl] Error 1
cmosiman-34078s:Brick cmosiman$ make test
python generate_brick.py
2021-01-13:12:24:56,027 WARNING [inference.py:128] Reasonable not installed; trying Allegro
Checking 56 containers
Removing old agraph
Traceback (most recent call last):
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.40/containers/6ca077e807cd9f8df90d2b804d76e9747cc69820d2d740b81981113c74e9aa41/exec

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate_brick.py", line 29, in <module>
    from bricksrc.quantities import quantity_definitions, get_units
  File "/Users/cmosiman/Github/Brick/bricksrc/quantities.py", line 13, in <module>
    g = sess.expand(g)
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/brickschema/inference.py", line 57, in expand
    self.g = self._owl_sess.expand(self.g)
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/brickschema/inference.py", line 146, in expand
    return self.sess.expand(graph)
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/brickschema/inference.py", line 334, in expand
    check_error(agraph.exec_run("chown -R agraph /tmp", user="root"))
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/docker/models/containers.py", line 196, in exec_run
    workdir=workdir,
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/docker/api/exec_api.py", line 80, in exec_create
    return self._result(res, True)
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/Users/cmosiman/.pyenv/versions/brick/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.40/containers/6ca077e807cd9f8df90d2b804d76e9747cc69820d2d740b81981113c74e9aa41/exec: Conflict ("Container 6ca077e807cd9f8df90d2b804d76e9747cc69820d2d740b81981113c74e9aa41 is not running")
make: *** [Brick.ttl] Error 1
cmosiman-34078s:Brick cmosiman$ docker ps -a | grep agra
6ca077e807cd        franzinc/agraph:v7.0.0                        "/entrypoint.sh"          About a minute ago   Exited (1) About a minute ago                                                    agraph
cmosiman-34078s:Brick cmosiman$ docker logs 6ca077e807cd
No config file found and AGRAPH_SUPER_USER and AGRAPH_SUPER_PASSWORD
variables are not set. Superuser is configured with the following
generated credentials:

  User:     admin
  Password: n6KisLyzfksBJ3Id

mkdir: cannot create directory '/agraph/data/settings': No space left on device
```

Lol I'm a dope. I just increased my disk image size so we'll see if this works...

**Comment by gtfierro** [comment]
No worries! The Allegro-based reasoner should do a better job of relaying the internal error messages.

That non-zero exit code is expected, so your output is in line with a functioning reasoner
