### ISSUE TITLE
make test broken

### ISSUE THREAD

**Issue by jbulow** [BrickSchema/Brick#218]
Following the instructions in CONTRIBUTING ends up with error:

``` 
make test
python generate_brick.py
Checking 3 containers
Traceback (most recent call last):
  File "/big/Brick/venv/lib/python3.9/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/big/Brick/venv/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.40/containers/create?name=agraph

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/big/Brick/venv/lib/python3.9/site-packages/docker/models/containers.py", line 811, in run
    container = self.create(image=image, command=command,
  File "/big/Brick/venv/lib/python3.9/site-packages/docker/models/containers.py", line 870, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/big/Brick/venv/lib/python3.9/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/big/Brick/venv/lib/python3.9/site-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/big/Brick/venv/lib/python3.9/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/big/Brick/venv/lib/python3.9/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/big/Brick/venv/lib/python3.9/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.40/containers/create?name=agraph: Not Found ("No such image: franzinc/agraph:v7.0.0")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/big/Brick/venv/lib/python3.9/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/big/Brick/venv/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.40/images/create?tag=v7.0.0&fromImage=franzinc%2Fagraph

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/big/Brick/generate_brick.py", line 29, in <module>
    from bricksrc.quantities import quantity_definitions, get_units
  File "/big/Brick/bricksrc/quantities.py", line 11, in <module>
    g.expand(profile="brick")
  File "/big/Brick/venv/lib/python3.9/site-packages/brickschema/graph.py", line 153, in expand
    return self.expand("owlrl+shacl+owlrl", backend=backend)
  File "/big/Brick/venv/lib/python3.9/site-packages/brickschema/graph.py", line 149, in expand
    self.expand(prf, backend=backend)
  File "/big/Brick/venv/lib/python3.9/site-packages/brickschema/graph.py", line 183, in expand
    self._inferbackend.expand(self)
  File "/big/Brick/venv/lib/python3.9/site-packages/brickschema/inference.py", line 134, in expand
    agraph = self._client.containers.run(
  File "/big/Brick/venv/lib/python3.9/site-packages/docker/models/containers.py", line 814, in run
    self.client.images.pull(image, platform=platform)
  File "/big/Brick/venv/lib/python3.9/site-packages/docker/models/images.py", line 446, in pull
    pull_log = self.client.api.pull(
  File "/big/Brick/venv/lib/python3.9/site-packages/docker/api/image.py", line 430, in pull
    self._raise_for_status(response)
  File "/big/Brick/venv/lib/python3.9/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/big/Brick/venv/lib/python3.9/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.40/images/create?tag=v7.0.0&fromImage=franzinc%2Fagraph: Internal Server Error ("Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)")
Makefile:4: recipe for target 'Brick.ttl' failed
make: *** [Brick.ttl] Error 1

```

**Comment by jbulow** [comment]
Missed the dependency on a working docker service to work with the Brick ontology.
