### ISSUE TITLE
Cannot run 'make test' successfully when setting up Brick development environment

### ISSUE THREAD

**Issue by wcrd** [BrickSchema/Brick#253]
Following the `CONTRIBUTING.md` guidelines.
Running 'make test' throws `AttributeError: 'OWLRLAllegroInferenceSession' object has no attribute '_client'` error. Full console output is below. I have made a pull request in the BrickSchema/py-brickschema with a change which will fix this (I think). See request BrickSchema/py-brickschema#48.

Thought I would open an issue here too incase anyone else was experiencing this problem.

I have tested the fix and it appears to work, however upon testing I get a '15 classes over-inferred' test failure on the current master; probably worth a second ticket (?):
`FAILED tests/test_measures_inference.py::test_measures_infers - AssertionError: There are 15 classes that are over-inferred`.

Full console output for 'make test' error:
```
(Brick-CGBt5J5p) wcrd@SA1035:~/programming/forked/Brick$ make test
mkdir -p extensions
python generate_brick.py
2021-04-06:14:01:43,302 ERROR   [inference.py:93] Could not connect to docker (Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))); defaulting to naive evaluation
Traceback (most recent call last):
  File "generate_brick.py", line 41, in <module>
    from bricksrc.quantities import quantity_definitions, get_units
  File "/home/wcrd/programming/forked/Brick/bricksrc/quantities.py", line 11, in <module>
    g.expand(profile="brick")
  File "/home/wcrd/.local/share/virtualenvs/Brick-CGBt5J5p/lib/python3.8/site-packages/brickschema/graph.py", line 226, in expand
    return self.expand("owlrl+shacl+owlrl", backend=backend)
  File "/home/wcrd/.local/share/virtualenvs/Brick-CGBt5J5p/lib/python3.8/site-packages/brickschema/graph.py", line 222, in expand
    self.expand(prf, backend=backend)
  File "/home/wcrd/.local/share/virtualenvs/Brick-CGBt5J5p/lib/python3.8/site-packages/brickschema/graph.py", line 244, in expand
    self._inferbackend = OWLRLAllegroInferenceSession()
  File "/home/wcrd/.local/share/virtualenvs/Brick-CGBt5J5p/lib/python3.8/site-packages/brickschema/inference.py", line 96, in __init__
    containers = self._client.containers.list(all=True)
AttributeError: 'OWLRLAllegroInferenceSession' object has no attribute '_client'
make: *** [Makefile:5: Brick.ttl] Error 1
```

**Comment by gtfierro** [comment]
Should be fixed in https://github.com/BrickSchema/py-brickschema/pull/48, available in `brickschema==0.3.2`
