### ISSUE TITLE
Brick.ttl file is missing causing unit test failure

### ISSUE THREAD

**Issue by Gamecock** [BrickSchema/Brick#438]
```================================================== short test summary info =================================================== 
ERROR tests/test_class_structure.py - FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Projects\\Brick\\Brick.ttl' 
ERROR tests/test_definitions.py - FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Projects\\Brick\\Brick.ttl'     
ERROR tests/test_hierarchy_inference.py
ERROR tests/test_inference.py - FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Projects\\Brick\\Brick.ttl'       
ERROR tests/test_no_inference.py - FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Projects\\Brick\\Brick.ttl'    
ERROR tests/test_quantities.py - FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Projects\\Brick\\Brick.ttl'      
ERROR tests/test_shapes.py - FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Projects\\Brick\\Brick.ttl'
ERROR tests/test_subclass_hierarchy.py - FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Projects\\Brick\\Brick...!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 8 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================== 3 warnings, 8 errors in 47.26s =============================================== 
```
System: Windows 10   Python 3.10.7

Since the test are passing in the build, I'm assuming this is operator error.  Happy to update the docs if someone can tell me what I'm doing wrong.
Have a couple things I'd like to update in the docs anyway..

**Comment by gtfierro** [comment]
Can you show how you are running the tests? You will need to generate `Brick.ttl` before the tests will work; this is easiest to do with the provided Makefile but you can also do the generation directly (basically `python generate_brick.py` after deps are installed)

**Comment by Gamecock** [comment]
I tried using Make based on the help in 'CONTRIBUTING.md':

```
$ make test
mkdir -p extensions
python tools/sort_definitions.py bricksrc/definitions.csv
Traceback (most recent call last):
  File "C:\Projects\Brick\Brick\tools\sort_definitions.py", line 10, in <module>
    data = list(reader)
  File "C:\Users\FinchMik\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 5393: character maps to <undefined>
make: *** [Makefile:5: Brick.ttl] Error 1
```
Then I tries using the help from 'README.md'
```Run tests by executing `pytest` in the top-level directory of this repository.```

**Comment by Gamecock** [comment]
I've got this down to:

```
Building wheel for Levenshtein-search (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'Levenshtein_search' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]
      ```
I installed the runtime tools since they do not need a VS liscence, I am using VSCOde
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by gtfierro** [comment]
I don't recall why Levenstein is in there, but it shouldn't be strictly necessary if you just want to build Brick. Can you share the full build trace so I can get a little context?

**Comment by Gamecock** [comment]
I tried running `make test` again and it generated a bunch of this error, 
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Projects\Brick\Brick\.venv\lib\site-packages\rdflib\term.py", line 2084, in _castLexicalToPython    
    return conv_func(lexical)  # type: ignore[arg-type]
  File "C:\Projects\Brick\Brick\.venv\lib\site-packages\rdflib\term.py", line 1652, in _parseHTML
    raise ImportError(
ImportError: HTML5 parser not available. Try installing html5lib <http://code.google.com/p/html5lib>
Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/1999/02/22-rdf-syntax-ns#HTML, Converter=<function _parseHTML at 0x000001E032571630>
Traceback (most recent call last):
  File "C:\Projects\Brick\Brick\.venv\lib\site-packages\rdflib\term.py", line 1645, in _parseHTML
    import html5lib
ModuleNotFoundError: No module named 'html5lib'
```
Tests then started running
========================================== short test summary info =========================================== 
FAILED tests/test_entity_properties.py::test_entity_property_type_inference - FileNotFoundError: [Errno 2] N...FAILED tests/test_inference.py::test_shacl_owl_equivalentclass - FileNotFoundError: [Errno 2] No such file o...====================== 2 failed, 53 passed, 1 skipped, 27 warnings in 781.39s (0:13:01) ====================== 
make: *** [Makefile:23: test] Error 1

**Comment by gtfierro** [comment]
Warnings are expected when running `generate_brick.py` but you should not have errors; can you paste what you are seeing?

Are you seeing that error above with the patch applied to `sort_definitions.py`?

**Comment by gtfierro** [comment]
Warnings are expected when running `generate_brick.py` but you should not have errors; can you paste what you are seeing?

Are you seeing that error above with the patch applied to `sort_definitions.py`?

**Comment by Gamecock** [comment]
No, I missed the patch instructions.  I will try that and respond. Sorry for the confusion.  I've been travelling the last couple of days.

**Comment by Gamecock** [comment]
With the patch:
`py generate_brick.py` does not generate any errors except for not having docker. Just a lot of warnings.
`pytest` has errors:
```=============================================== short test summary info ================================================ 
FAILED tests/test_entity_properties.py::test_entity_property_type_inference - FileNotFoundError: [Errno 2] No such fil...FAILED tests/test_inference.py::test_shacl_owl_equivalentclass - FileNotFoundError: [Errno 2] No such file or director...========================== 2 failed, 53 passed, 1 skipped, 13 warnings in 1270.61s (0:21:10) =========================== ```

Make still generates an error:
```$ make test
mkdir -p extensions
python tools/sort_definitions.py bricksrc/definitions.csv
python generate_brick.py
C:\Projects\Brick\Brick\.venv\lib\site-packages\brickschema\graph.py:240: UserWarning: Could not load Reasonable reasoner. Needs 'reasonable' option during install.
  warn(
2022-10-11:17:46:01,387 ERROR   [inference.py:98] Could not connect to docker (Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')); defaulting to naive evaluation
C:\Projects\Brick\Brick\.venv\lib\site-packages\brickschema\graph.py:250: UserWarning: Could not load Allegro reasoner. Needs 'allegro' option during install.
  warn(
C:\Projects\Brick\Brick\.venv\lib\site-packages\brickschema\graph.py:240: UserWarning: Could not load Reasonable reasoner. Needs 'reasonable' option during install.
  warn(
2022-10-11:17:46:20,399 ERROR   [inference.py:98] Could not connect to docker (Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')); defaulting to naive evaluation
2022-10-11:17:46:28,588 WARNING [generate_brick.py:297] Property 'tags' not defined for https://brickschema.org/schema/Brick#Measurable
2022-10-11:17:46:28,588 WARNING [generate_brick.py:297] Property 'tags' not defined for https://brickschema.org/schema/Brick#Measurable
2022-10-11:17:46:29,662 WARNING [generate_brick.py:297] Property 'tags' not defined for https://brickschema.org/schema/Brick#Lighting
2022-10-11:17:46:29,683 WARNING [generate_brick.py:297] Property 'tags' not defined for https://brickschema.org/schema/Brick#PV_Generation_System
Traceback (most recent call last):
  File "C:\Projects\Brick\Brick\generate_brick.py", line 880, in <module>
    add_definitions()
  File "C:\Projects\Brick\Brick\generate_brick.py", line 644, in add_definitions
    term = URIRef(definition[0])
IndexError: list index out of range
make: *** [Makefile:6: Brick.ttl] Error 1
(.venv)```

**Comment by Gamecock** [comment]
@gtfierro, is there value to either the project or to my understanding of Brick to address the Warnings during tests?  I'm assuming they are caused by changes in Brick that were not addressed in the test suite.
