### ISSUE TITLE
Cannot access to  owl:imports <https://brickschema.org/schema/1.0.3/Brick> cause it's missing the final .ttl 

### ISSUE THREAD

**Issue by cristinacarones** [BrickSchema/Brick#50]

**Comment by gtfierro** [comment]
Thanks for the issue! Can you say more about where you're getting this error?

**Comment by cristinacarones** [comment]
So when i try to import the ontology  in protegè, when i use the URI import mode , it returns me an error , cause he can't find any ontology. 
i use this URI  **http://brickschema.org/ttl/BrickTag.ttl** 
When i open it with the browser i correctly find it but when i use it to import in protegè it doesn't works.
Can u help me about this issue?
thank you

**Comment by jbkoh** [comment]
This is probably because we do not direct "https://brickschema.org/schema/1.0.2/Brick" to its actual file, "https://brickschema.org/schema/1.0.2/Brick.ttl" in the host. We need to add the alias to the website.

Another TODO: we need to update the link to the most recent version (or remove away.)

**Comment by jbkoh** [comment]
@gtfierro I just found that redirect in Hugo with Github Pages is not that easy. Do you have any ideas on it?
(ref: https://discourse.gohugo.io/t/how-can-i-create-a-redirect-for-a-non-content-file/5592/11)

This would be unnecessary once we have a new homepage though :)

**Comment by cristinacarones** [comment]
> This is probably because we do not direct "https://brickschema.org/schema/1.0.2/Brick" to its actual file, "https://brickschema.org/schema/1.0.2/Brick.ttl" in the host. We need to add the alias to the website.
> 
> TODO:
> 
> 1. We need to update the link to the most recent version (or remove away.)
> 2. Investigate why Brick.ttl is imported inside BrickTag.ttl, and possibly fix.
> 3. Make aliases at the website.
> 
> UPDATE: I now doubt that if the problem is related to the URL address because the error message in Protege is explicitly complaining about the original link with .ttl extension. I don't know the exact request of Protege, so cannot easily debug.


Unfortunately the error in protege is not always replicable, but if you try to use an online OWL validator, like  http://mowl-power.cs.man.ac.uk:8080/validator/
you can see this error , it seems like is a connection error, but not related to the old version cause in the ttl i can see correctly the 1.0.3 version

org.semanticweb.owlapi.io.OWLOntologyCreationIOException: Received fatal alert: handshake_failure
	at uk.ac.manchester.cs.owl.owlapi.ParsableOWLOntologyFactory.loadOWLOntology(ParsableOWLOntologyFactory.java:214)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:827)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:773)
	at uk.ac.manchester.cs.owl.validator.Validator.doValidation(Validator.java:101)
	at uk.ac.manchester.cs.owl.validator.Validator.doPost(Validator.java:85)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1023)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1961)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1077)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1339)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1323)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:515)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStream(AbstractOWLParser.java:130)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputSource(AbstractOWLParser.java:227)
	at org.coode.owlapi.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:118)
	at uk.ac.manchester.cs.owl.owlapi.ParsableOWLOntologyFactory.loadOWLOntology(ParsableOWLOntologyFactory.java:206)
	... 22 more

**Comment by gtfierro** [comment]
It does seem like the online validation tool can't handle HTTPS links, and its getting some 403 error with the non-HTTPS links, which is strange. Too bad we get the Java stacktrace instead of a useful error message.

It doesn't look like we're doing most of this any differently than other people (e.g. [this rdf.ttl file](https://github.com/dvcama/LodView/blob/master/src/main/webapp/WEB-INF/ontologies/rdfs.ttl)). http://brickschema.org/schema/1.0.3/Brick.ttl is the authoritative link for version 1.0.3.

The problem here is specifically the change in usage of "owl:imports" from OWL 1 to OWL 2. OWL 2 expects a URL that can be fetched, and the current release of Brick elides the .ttl. This should be a simple fix in the TTL file itself, and shouldn't require any redirects on the site.

@cristinacarones where are you getting the http://brickschema.org/ttl/BrickTag.ttl link from?

**Comment by cristinacarones** [comment]
i get all the link from this page 
http://brickschema.org/schema/1.0.3/

**Comment by gtfierro** [comment]
@christinacarones I'm not seeing any link on that page to
http://brickschema.org/ttl/BrickTag.ttl . That link isn't mentioned in any
of the 1.0.3 schema files either, so its not clear where that link is
coming from.

Can you try adding the .ttl to the owl import statement in a downloaded
version of the Brick schema to see if that fixes the issue?

**Comment by cristinacarones** [comment]
Sorry maybe i made i mistake when i wrote the first time the link anyway i have the same problem importing this link http://brickschema.org/schema/1.0.3/Brick.ttl in protege

and the problem is connection

Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://brickschema.org/schema/1.0.3/Brick.ttl

so i suppose is a privilege access problem do u see?

**Comment by gtfierro** [comment]
I think this is a problem with the tool, because I have no problems downloading that link from other HTTP tools. You can try replacing `http://` with `https://` to see if that fixes the issue?

**Comment by jbkoh** [comment]
I am closing this one as the discussion has been inactive for a while. Please reopen it if this is still a problem.

**Comment by majidaldo** [comment]
> 



> It does seem like the online validation tool can't handle HTTPS links, and its getting some 403 error with the non-HTTPS links, which is strange. Too bad we get the Java stacktrace instead of a useful error message.
> 
> It doesn't look like we're doing most of this any differently than other people (e.g. [this rdf.ttl file](https://github.com/dvcama/LodView/blob/master/src/main/webapp/WEB-INF/ontologies/rdfs.ttl)). http://brickschema.org/schema/1.0.3/Brick.ttl is the authoritative link for version 1.0.3.
> 
> The problem here is specifically the change in usage of "owl:imports" from OWL 1 to OWL 2. OWL 2 expects a URL that can be fetched, and the current release of Brick elides the .ttl. This should be a simple fix in the TTL file itself, and shouldn't require any redirects on the site.
> 
> @cristinacarones where are you getting the http://brickschema.org/ttl/BrickTag.ttl link from?

still an issue since `<https://brickschema.org/schema/1.3/Brick> a owl:Ontology ;` . this url 404s.

**Comment by gtfierro** [comment]
Weird! I could have sworn that was working before -- I'll look into it and see if I can fix it

**Comment by gtfierro** [comment]
Can you file a new issue on this, @majidaldo ?

**Comment by gtfierro** [comment]
Should be fixed now!
